### ISSUE TITLE
It is hard to git clone

### ISSUE THREAD

**Issue by unavailable-2374** [BioinformaticsToolsmith/Look4LTRs#1]
hello 

This tool is amazing, i used it on a simulate data, it worked very well !

But I dont know is the network too wrong to cannot git clone it or some another reason .

I try git clone so many time maybe 10~20 until I make it.

really hope to solve this problem.

thanks ~
Cao

**Comment by AnthonyGarza124** [comment]
Hello!

If I understand correctly, you were having trouble git cloning the repo? We git cloned it on our side using a separate machine and had no problem. Most likely this problem has to do with GitHub itself and is not on our side. If the git clone does not work next time, perhaps you should try downloading the Zip file instead. If there was any other problem aside from the git cloning, please provide the error messages and I'll see what I can do! 

Thank you very much and have a wonderful day!

Best regards,
Anthony Garza

**Comment by unavailable-2374** [comment]
hello

yes, I did. It is really hard to me to git cloning the repo. I wanna use your tools to make a protocol, if the Zip file is ready that's perfect. 

thanks a lot !

Best regards,
Shuo Cao
