### ISSUE TITLE
how to give fasta file path

### ISSUE THREAD

**Issue by herman-einstein** [BioinformaticsToolsmith/Look4LTRs#4]
May I know how to give the path? I keep having "does not exist!" error

**Comment by AnthonyGarza124** [comment]
Hello,

Be sure to provide the directory, not the file itself! If you have only one file you want to predict on, be sure to provide a directory with only the fasta file inside of it. Use the -f parameter.

So:

look4ltrs -f /x/y/fasta_directory [other parameters]

Best Regards,
Anthony Garza
